/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */
#include <stdint.h>

#define RCC_AHB1ENR (*(volatile uint32_t*)0x40023830)
#define GPIOC_MODER (*(volatile uint32_t*)0x40020800)
#define GPIOC_ODR   (*(volatile uint32_t*)0x40020814)

#define SCB_VTOR (*(volatile uint32_t*)0xE000ED08)

#define APP_ADDRESS 0x08008000

typedef void (*pFunction)(void);

void delay(void)
{
    for(volatile uint32_t i = 0; i < 100000; i++);
}

int main(void)
{
    RCC_AHB1ENR |= (1 << 2);

    GPIOC_MODER &= ~(3 << (13 * 2));
    GPIOC_MODER |=  (1 << (13 * 2));

    /* Fast blink 10 times */
    for(int i = 0; i < 10; i++)
    {
        GPIOC_ODR ^= (1 << 13);
        delay();
    }

    uint32_t appStack = *(volatile uint32_t*)APP_ADDRESS;
    uint32_t appResetHandler = *(volatile uint32_t*)(APP_ADDRESS + 4);

    /* Move vector table */
    SCB_VTOR = APP_ADDRESS;

    /* Set stack pointer */
    __asm volatile("MSR MSP, %0" : : "r"(appStack));

    /* Jump */
    pFunction JumpToApplication = (pFunction)appResetHandler;

    JumpToApplication();

    while(1);
}
